apiVersion: v1
kind: ServiceAccount
metadata:
  name: appstudio-pipeline
secrets:
  - name: quay-push-secret
  - name: registry-redhat-io-pull-secret
  - name: quay-push-secret-konflux-ci
imagePullSecrets:
  - name: quay-push-secret
  - name: registry-redhat-io-pull-secret
  - name: quay-push-secret-konflux-ci
